import test from "node:test";
import assert from "node:assert/strict";
import "../../www/vplan.js";
const V=globalThis.XyzVPlan;
const slots=[{std:"1,2",von:"08:00",bis:"09:30"},{std:"3/4",von:"09:45",bis:"11:15"},{std:"5",von:"11:30",bis:"12:15"}];
const e=(x={})=>({datum:"2026-09-14",slot:"1",art:"vertretung",fachAlt:"MA",...x});

test("01 exakter Block 1,2",()=>assert.equal(V.mapSlot("1,2",slots),0));
test("02 Slash-Block 3/4",()=>assert.equal(V.mapSlot("3/4",slots),1));
test("03 Einzelstunde in eindeutigem Block",()=>assert.equal(V.mapSlot("2",slots),0));
test("04 unbekannte Stunde",()=>assert.equal(V.mapSlot("9",slots),null));
test("05 fehlende Stunde",()=>assert.equal(V.mapSlot("",slots),null));
test("06 Mehrdeutigkeit wird nicht geraten",()=>assert.equal(V.mapSlot("1,2",[{std:"1,2,3"},{std:"1,2,4"}]),null));
test("07 normaler Unterrichtseintrag",()=>assert.equal(V.normalisieren(e()).fachAlt,"MA"));
test("08 Ausfall",()=>assert.equal(V.normalisieren(e({entfaellt:true})).entfaellt,true));
test("09 Raumänderung",()=>assert.equal(V.normalisieren(e({raumAlt:"101",raumNeu:"204"})).raumNeu,"204"));
test("10 Lehreränderung",()=>assert.equal(V.normalisieren(e({lehrerAlt:"MÜ",lehrerNeu:"SC"})).lehrerNeu,"SC"));
test("11 Fachänderung",()=>assert.equal(V.normalisieren(e({fachNeu:"PH"})).fachNeu,"PH"));
test("12 Kombination bleibt erhalten",()=>{const x=V.normalisieren(e({fachNeu:"PH",raumNeu:"204",lehrerNeu:"SC"}));assert.deepEqual([x.fachNeu,x.raumNeu,x.lehrerNeu],["PH","204","SC"])});
test("13 Zusatzunterricht",()=>assert.equal(V.normalisieren(e({art:"zusatz"})).art,"zusatz"));
test("14 ungültiges Datum verworfen",()=>assert.equal(V.normalisieren(e({datum:"14.09.2026"})),null));
test("15 mehrere Vertretungen am Tag",()=>assert.equal(V.mappeTag([e(),e({slot:"3",fachAlt:"PH"})],slots).overlay.length,2));
test("16 unbekannter Slot wird Tageshinweis",()=>assert.equal(V.mappeTag([e({slot:"99"})],slots).hinweise.length,1));
test("17 identischer Abruf dupliziert nicht",()=>assert.equal(V.cacheAktualisieren([e({remoteId:"a"})],[e({remoteId:"a"})]).length,1));
test("18 geänderte Vertretung ersetzt alten Stand",()=>{const c=V.cacheAktualisieren([e({remoteId:"a",raumNeu:"101"})],[e({remoteId:"a",raumNeu:"204"})]);assert.equal(c.length,1);assert.equal(c[0].raumNeu,"204")});
test("19 mehrere Änderungen gleicher Slot mit IDs",()=>assert.equal(V.cacheAktualisieren([], [e({remoteId:"a"}),e({remoteId:"b",art:"hinweis"})]).length,2));
test("20 Cache nach Datum",()=>assert.equal(V.cacheFuerDatum([e(),e({datum:"2026-09-15"})],"2026-09-14").length,1));
test("21 Cachealter",()=>assert.equal(V.cacheAlterMinuten([e({abgerufenAm:"2026-09-14T07:00:00Z"})],Date.parse("2026-09-14T07:42:00Z")),42));
test("22 Steuerzeichen entfernt",()=>assert.equal(V.text("MA\u0000<script>"),"MA<script>"));
test("23 HTML bleibt Textdaten und wird nicht interpretiert",()=>assert.equal(V.normalisieren(e({hinweis:"<img src=x onerror=alert(1)>"})).hinweis,"<img src=x onerror=alert(1)>"));
test("24 Client verweigert ohne native Brücke",async()=>{await assert.rejects(()=>new V.VPlanClient({bridge:null,adapter:{}}).abrufen(),x=>x.code==="BRIDGE_FEHLT")});
test("25 Client verweigert unbekanntes Portalprotokoll",async()=>{const bridge={request:async()=>({status:200,body:"x"})};await assert.rejects(()=>new V.VPlanClient({bridge}).abrufen(),x=>x.code==="PROTOKOLL_FEHLT")});
test("26 HTTP 401 wird Loginfehler",async()=>{const bridge={request:async()=>({status:401,body:""})},adapter={anfrage:async()=>({url:"https://example.invalid"}),parse:async()=>[]};await assert.rejects(()=>new V.VPlanClient({bridge,adapter}).abrufen(),x=>x.code==="LOGIN_FEHLER")});
test("27 HTTP Fehler bleibt HTTP Fehler",async()=>{const bridge={request:async()=>({status:503,body:""})},adapter={anfrage:async()=>({}),parse:async()=>[]};await assert.rejects(()=>new V.VPlanClient({bridge,adapter}).abrufen(),x=>x.code==="HTTP_FEHLER"&&x.status===503)});
test("28 Parserfehler wird gekapselt",async()=>{const bridge={request:async()=>({status:200,body:"kaputt"})},adapter={anfrage:async()=>({}),parse:async()=>{throw new Error("bad")}};await assert.rejects(()=>new V.VPlanClient({bridge,adapter}).abrufen(),x=>x.code==="PARSER_FEHLER")});
test("29 Parser muss Array liefern",async()=>{const bridge={request:async()=>({status:200,body:"{}"})},adapter={anfrage:async()=>({}),parse:async()=>({})};await assert.rejects(()=>new V.VPlanClient({bridge,adapter}).abrufen(),x=>x.code==="PARSER_FEHLER")});
test("30 Erfolgsfall stempelt Abrufzeit",async()=>{const bridge={request:async()=>({status:200,body:"[]"})},adapter={anfrage:async()=>({}),parse:async()=>[e()]};const r=await new V.VPlanClient({bridge,adapter}).abrufen();assert.ok(r[0].abgerufenAm)});
test("31 Secure Storage Setter nutzt Brücke",async()=>{let got;const bridge={request:async()=>({}),secureSet:async x=>(got=x,{ok:true})};await new V.VPlanClient({bridge,adapter:{}}).geheimnisSetzen("passwort","secret");assert.deepEqual(got,{key:"passwort",value:"secret"})});
